services:
  db:
    container_name: ${POSTGRES_DB}
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
volumes:
  pgdata: